# Generated by Django 3.2.9 on 2021-11-29 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('usuario_creacion', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_actualizacion', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True)),
                ('ruc', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Clientes',
                'db_table': 'cobranza_cliente',
                'ordering': ['-id'],
            },
        ),
    ]
