# Generated by Django 3.2.9 on 2021-12-01 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bancos', '0001_initial'),
        ('clientes', '0001_initial'),
        ('extractos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoAbono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('usuario_creacion', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_actualizacion', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'cobranza_estado_abono',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Planilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('usuario_creacion', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_actualizacion', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True)),
                ('fecha', models.DateField()),
                ('total_inhabilitado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_identificado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_por_identificar', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cuenta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bancos.cuentabancaria')),
                ('extracto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='extractos.extracto')),
            ],
            options={
                'verbose_name': 'planilla',
                'verbose_name_plural': 'panillas',
                'db_table': 'cobranza_planilla',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('usuario_creacion', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_actualizacion', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True)),
                ('fecha', models.DateField()),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('numero_operacion', models.CharField(max_length=50)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.cliente')),
                ('estado_abono', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='planillas.estadoabono')),
                ('planilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='planillas.planilla')),
            ],
            options={
                'verbose_name': 'abono',
                'verbose_name_plural': 'abonos',
                'db_table': 'cobranza_abono',
                'ordering': ['-id'],
            },
        ),
    ]
