# Generated by Django 3.2.9 on 2021-12-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planillas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abono',
            name='referencia',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
    ]
